"""empty message

Revision ID: ccae33403d20
Revises: 
Create Date: 2023-01-03 23:26:30.703870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccae33403d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('unit_number', sa.String(length=64), nullable=False),
    sa.Column('street_address', sa.String(length=240), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('zip_code', sa.String(length=32), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_date_registered'), ['date_registered'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('managers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_managers_shop_id_shops')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_managers_user_id_users'))
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.Column('date_retired', sa.DateTime(), nullable=True),
    sa.Column('primary_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_shop_id'], ['shops.id'], name=op.f('fk_programs_primary_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_date_registered'), ['date_registered'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_date_retired'), ['date_retired'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_primary_shop_id'), ['primary_shop_id'], unique=False)

    op.create_table('shop_subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_subscriptions_shop_id_shops')),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], name=op.f('fk_shop_subscriptions_subscriber_id_users'))
    )
    op.create_table('staffs',
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_staffs_shop_id_shops')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staffs_staff_id_users'))
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('access_expiration', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_expiration', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_access_token'), ['access_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_refresh_token'), ['refresh_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('program_subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_program_subscriptions_program_id_programs')),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], name=op.f('fk_program_subscriptions_subscriber_id_users'))
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_staff_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=560), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_purchases_program_id_programs')),
    sa.ForeignKeyConstraint(['purchase_staff_id'], ['users.id'], name=op.f('fk_purchases_purchase_staff_id_users')),
    sa.ForeignKeyConstraint(['purchase_user_id'], ['users.id'], name=op.f('fk_purchases_purchase_user_id_users')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_purchases_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_date_purchased'), ['date_purchased'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchase_staff_id'), ['purchase_staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchase_user_id'), ['purchase_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_shop_id'), ['shop_id'], unique=False)

    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redemption_user_id', sa.Integer(), nullable=True),
    sa.Column('redemption_staff_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('date_redeemed', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=560), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_redemptions_program_id_programs')),
    sa.ForeignKeyConstraint(['redemption_staff_id'], ['users.id'], name=op.f('fk_redemptions_redemption_staff_id_users')),
    sa.ForeignKeyConstraint(['redemption_user_id'], ['users.id'], name=op.f('fk_redemptions_redemption_user_id_users')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_redemptions_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redemptions'))
    )
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemptions_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_date_redeemed'), ['date_redeemed'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_redemption_staff_id'), ['redemption_staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_redemption_user_id'), ['redemption_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemptions_shop_id'), ['shop_id'], unique=False)

    op.create_table('shop_programs',
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_shop_programs_program_id_programs')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_programs_shop_id_shops'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_programs')
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemptions_shop_id'))
        batch_op.drop_index(batch_op.f('ix_redemptions_redemption_user_id'))
        batch_op.drop_index(batch_op.f('ix_redemptions_redemption_staff_id'))
        batch_op.drop_index(batch_op.f('ix_redemptions_program_id'))
        batch_op.drop_index(batch_op.f('ix_redemptions_points'))
        batch_op.drop_index(batch_op.f('ix_redemptions_date_redeemed'))
        batch_op.drop_index(batch_op.f('ix_redemptions_cost'))

    op.drop_table('redemptions')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_shop_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchase_staff_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_program_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_points'))
        batch_op.drop_index(batch_op.f('ix_purchases_date_purchased'))
        batch_op.drop_index(batch_op.f('ix_purchases_cost'))

    op.drop_table('purchases')
    op.drop_table('program_subscriptions')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_tokens_access_token'))

    op.drop_table('tokens')
    op.drop_table('staffs')
    op.drop_table('shop_subscriptions')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_primary_shop_id'))
        batch_op.drop_index(batch_op.f('ix_programs_date_retired'))
        batch_op.drop_index(batch_op.f('ix_programs_date_registered'))

    op.drop_table('programs')
    op.drop_table('managers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_email'))
        batch_op.drop_index(batch_op.f('ix_shops_date_registered'))

    op.drop_table('shops')
    # ### end Alembic commands ###
